export const GEOLOCATION_WEATHER_DATA: string = 'GEOLOCATION_WEATHER_DATA'

export const EXPAND_FORECAST_DATA: string = 'EXPAND_FORECAST_DATA'

export const ITEM_LIST_ADD_ITEM: string = 'ITEM_LIST_ADD_ITEM'
export const ITEM_LIST_DELETE_ITEM: string = 'ITEM_LIST_DELETE_ITEM'
export const ITEM_LIST_ADD_RESPONSE: string = 'ITEM_LIST_ADD_RESPONSE'
export const ITEM_LIST_RESTORE: string = 'ITEM_LIST_RESTORE'