export const GEOLOCATION_WEATHER_DATA = 'GEOLOCATION_WEATHER_DATA'

export const EXPAND_FORECAST_DATA = 'EXPAND_FORECAST_DATA'

export const ITEM_LIST_ADD_ITEM = 'ITEM_LIST_ADD_ITEM'
export const ITEM_LIST_DELETE_ITEM = 'ITEM_LIST_DELETE_ITEM'
export const ITEM_LIST_ADD_RESPONSE = 'ITEM_LIST_ADD_RESPONSE'
export const ITEM_LIST_RESTORE = 'ITEM_LIST_RESTORE'